language: node_js
node_js:
   - "8"
dist: rusty
services:
   - mongodb
cache:
   directories:
      - node_modules
install:
   - npm install
script:
   - nohup npm start &
   - sleep 3
   - npm run test
